import localFont from "next/font/local";
import "./globals.css";
import SocialLInks from "./[components]/others/SocialLInks";
import Navbar from "./[components]/navbar/Navbar";
import Footer from "./[components]/footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import 'react-toastify/dist/ReactToastify.css';
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed z-50 left-0 top-1/2  ">
<SocialLInks/>
</div>
<Navbar/>
        {children}

        <Footer/>
      </body>
    </html>
  );
}
